"""
Sistema de traducciones para MateKids - Soporta Español e Inglés
Los emojis se mantienen para la interfaz UI, pero se manejan correctamente en PDF
"""

TRANSLATIONS = {
    "es": {
        # Login
        "welcome": "¡Bienvenido!",
        "choose_avatar": "Elige tu avatar",
        "your_name": "¿Cómo te llamas?",
        "start_playing": "¡Empezar a jugar!",
        "name_required": "Escribe tu nombre",
        
        # Home
        "greeting": "Hola",
        "stars": "Estrellas",
        "choose_level": "Elige un nivel",
        "level_1": "🟢 Nivel 1",
        "level_2": "🔵 Nivel 2",
        "level_3": "🟣 Nivel 3",
        "generate_pdf": "📚 Generar Cuadernillo PDF",
        "pdf_saved": "✅ PDF guardado en: data/",
        "pdf_error": "❌ Error al generar PDF",
        "no_activities": "⚠️ No hay actividades para este nivel",
        
        # Game
        "very_good": "⭐ ¡Muy bien! ⭐",
        "try_again": "🤔 Intenta otra vez",
        "almost": "Casi. Contemos otra vez.",
        
        # Results
        "congratulations": "🏆 ¡Felicidades",
        "good_job": "🎯 Buen trabajo",
        "finished": "🏆 ¡Terminaste!",
        "got_stars": "Conseguiste",
        "stars_in_level": "estrellas en el nivel",
        "generate_diploma": "🏆 Generar mi Diploma",
        "diploma_saved": "✅ ¡Diploma guardado en: data/",
        "diploma_error": "❌ Error al generar diploma",
        "back_home": "Volver al Inicio 🏠",
        
        # Diploma (sin emojis para PDF)
        "diploma_title": "DIPLOMA DE RECONOCIMIENTO",
        "diploma_subtitle": "Se otorga el presente reconocimiento a:",
        "completed_level": "Por haber completado exitosamente el Nivel",
        "with_grade": "con una calificación de",
        "stars_text": "estrellas",
        "date": "Fecha",
        "teacher_signature": "Firma del Maestro/a",
        "footer": "Generado por MateKids - ¡Aprender es divertido!",
        
        # PDF Workbook (sin emojis para PDF)
        "workbook_title": "Cuadernillo de Matemáticas - Nivel",
        "workbook_subtitle": "Resuelve los siguientes ejercicios",
        "footer_workbook": "MateKids - Aprendiendo matemáticas con diversión",
        
        # PDF específico con emojis (se usan en el PDF directamente)
        "pdf_title": "Cuadernillo de Matemáticas",
        "pdf_name_label": "Nombre:",
        "pdf_date_label": "Fecha:",
    },
    
    "en": {
        # Login
        "welcome": "Welcome!",
        "choose_avatar": "Choose your avatar",
        "your_name": "What's your name?",
        "start_playing": "Start Playing!",
        "name_required": "Please enter your name",
        
        # Home
        "greeting": "Hello",
        "stars": "Stars",
        "choose_level": "Choose a level",
        "level_1": "🟢 Level 1",
        "level_2": "🔵 Level 2",
        "level_3": "🟣 Level 3",
        "generate_pdf": "📚 Generate Workbook PDF",
        "pdf_saved": "✅ PDF saved in: data/",
        "pdf_error": "❌ Error generating PDF",
        "no_activities": "⚠️ No activities for this level",
        
        # Game
        "very_good": "⭐ Very Good! ⭐",
        "try_again": "🤔 Try Again",
        "almost": "Almost. Let's count again.",
        
        # Results
        "congratulations": "🏆 Congratulations",
        "good_job": "🎯 Good Job",
        "finished": "🏆 You Finished!",
        "got_stars": "You got",
        "stars_in_level": "stars in level",
        "generate_diploma": "🏆 Generate My Diploma",
        "diploma_saved": "✅ Diploma saved in: data/",
        "diploma_error": "❌ Error generating diploma",
        "back_home": "Back to Home 🏠",
        
        # Diploma (sin emojis para PDF)
        "diploma_title": "CERTIFICATE OF ACHIEVEMENT",
        "diploma_subtitle": "This certificate is awarded to:",
        "completed_level": "For successfully completing Level",
        "with_grade": "with a score of",
        "stars_text": "stars",
        "date": "Date",
        "teacher_signature": "Teacher's Signature",
        "footer": "Generated by MateKids - Learning is Fun!",
        
        # PDF Workbook (sin emojis para PDF)
        "workbook_title": "Math Workbook - Level",
        "workbook_subtitle": "Solve the following exercises",
        "footer_workbook": "MateKids - Learning math with fun",
        
        # PDF específico con emojis
        "pdf_title": "Math Workbook",
        "pdf_name_label": "Name:",
        "pdf_date_label": "Date:",
    }
}

def get_text(lang: str, key: str) -> str:
    """Obtiene texto traducido. Si no existe, devuelve en inglés como fallback."""
    if lang not in TRANSLATIONS:
        lang = "en"
    return TRANSLATIONS.get(lang, {}).get(key, TRANSLATIONS["en"].get(key, key))

def get_text_without_emojis(lang: str, key: str) -> str:
    """Obtiene texto traducido sin emojis para usar en PDF con fuentes que no los soportan."""
    text = get_text(lang, key)
    # Eliminar emojis comunes
    import re
    emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002500-\U00002BEF"  # chinese char
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"  # dingbats
        u"\u3030"
        "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text).strip()

def get_available_languages() -> list:
    """Retorna lista de idiomas disponibles."""
    return list(TRANSLATIONS.keys())